//go:build js && wasm

package auth

import (
	"context"
	"time"

	h "github.com/monstercameron/GoWebComponents/v5/html/shorthand"
	gwci18n "github.com/monstercameron/GoWebComponents/v5/i18n"
	"github.com/monstercameron/GoWebComponents/v5/router"
	"github.com/monstercameron/GoWebComponents/v5/ui"

	affv1 "github.com/monstercameron/AnimeFeedFlux/gen/aff/v1"
	afi18n "github.com/monstercameron/AnimeFeedFlux/web/i18n"
	"github.com/monstercameron/AnimeFeedFlux/web/shell"
)

// RecoverPageProps wires /recover to the shell's live control-plane
// client. OnElevated fires the moment RecoverWithCode succeeds — the
// shell uses it to transition ANON -> ELEVATED
// (web/appstate.EvRecoveryCodeAccepted) so the route guard starts
// enforcing D1-11 immediately, not only after this component re-renders.
// OnComplete fires once the chosen elevated action (password reset OR
// TOTP re-enrollment — see doc.go assumption #3) succeeds and the
// elevated session has ended server-side; the shell uses it to
// transition ELEVATED -> ANON (web/appstate.EvRecoveryComplete).
type RecoverPageProps struct {
	Client     RecoverClient
	OnElevated func(session *affv1.Session)
	OnComplete func()
}

// keyRecoverSavedConfirm labels the "I've saved this" checkbox that gates
// RecoverStepDone's "Go to sign in" button after a TOTP re-enrollment
// (never after a plain password reset, which shows no shown-once secret).
// Same missing-catalogue situation as backoff_display.go's
// keyConnectionUnreachable/keyBackoffCleared — web/i18n is out of this
// task's allowed paths, so this references a key the catalogue owner still
// needs to add rather than a raw literal, following
// web/pages/settings/wiring.go's identical precedent.
//
// Why this exists at all: PLAN.md §4/§12.2 says a re-enrolled TOTP
// secret's QR/otpauth URI is "shown once; never retrievable again" — the
// same "shown once" property recovery codes have, just for a different
// secret (this package never renders actual recovery codes; those are
// generated by `aff admin init` and regenerated by Settings' out-of-scope
// RegenerateRecoveryCodes, neither reachable from here). Losing this
// screen without having saved it means the TOTP secret is gone and
// break-glass on the box is the only way back in — exactly the cost a
// stray click on "Go to sign in" would otherwise risk paying silently.
const keyRecoverSavedConfirm = "recoverSavedConfirmLabel"

// RecoverPage is /recover's root component (PLAN.md §12.2, D1-07..11).
func RecoverPage(props RecoverPageProps) ui.Node {
	intl := gwci18n.UseI18n()
	t := intl.NS(afi18n.NSAuth)
	tc := intl.NS(afi18n.NSCommon)
	nav := router.UseNavigate()
	announcer := ui.UseAnnouncer()
	focus := ui.UseFocusManager()

	form := ui.UseState(NewRecoverForm())
	// errKey mirrors login.go's errKey — see that file's doc comment for
	// why a KEY rather than a bool, and backoff_display.go's AuthErrorKey
	// for the disconnected-vs-generic distinction it encodes.
	errKey := ui.UseState("")
	// backoffActive mirrors login.go's — tracks whether the code-entry
	// step's backoff was announced as started, gating the completion
	// announcement (ShouldAnnounceBackoffCleared).
	backoffActive := ui.UseState(false)
	// confirmedSaved gates RecoverStepDone's "Go to sign in" button after a
	// TOTP re-enrollment — see keyRecoverSavedConfirm's doc comment.
	confirmedSaved := ui.UseState(false)
	provisioningURI := ui.UseState("")
	clock := ui.UseState(time.Now())

	codeID := ui.UseId() + "-code"
	newPasswordID := ui.UseId() + "-newpw"
	confirmPasswordID := ui.UseId() + "-confirmpw"
	errorID := ui.UseId() + "-error"
	reenrollHeadingID := ui.UseId() + "-reenroll-heading"
	savedConfirmID := ui.UseId() + "-savedconfirm"

	ui.UseMount(func() func() {
		ticker := time.NewTicker(time.Second)
		stop := make(chan struct{})
		go func() {
			for {
				select {
				case <-ticker.C:
					clock.Set(time.Now())
				case <-stop:
					return
				}
			}
		}()
		return func() {
			ticker.Stop()
			close(stop)
		}
	})

	now := clock.Get()
	f := form.Get()

	handleCode := ui.UseEvent(func(e ui.InputEvent) {
		form.Set(form.Get().SetCode(e.GetValue()))
	})
	handleNewPassword := ui.UseEvent(func(e ui.InputEvent) {
		form.Set(form.Get().SetNewPassword(e.GetValue()))
	})
	handleConfirmPassword := ui.UseEvent(func(e ui.InputEvent) {
		form.Set(form.Get().SetConfirmPassword(e.GetValue()))
	})

	// recoverFocusSelector maps RecoverFocusTargetForStep's symbolic result
	// onto this render's actual element IDs (mirrors login.go's
	// loginFocusSelector).
	recoverFocusSelector := func(target RecoverFocusTarget) string {
		switch target {
		case RecoverFocusCode:
			return "#" + codeID
		case RecoverFocusNewPassword:
			return "#" + newPasswordID
		case RecoverFocusReenrollHeading:
			return "#" + reenrollHeadingID
		case RecoverFocusError:
			return "#" + errorID
		default:
			return ""
		}
	}

	handleCodeSubmit := ui.UseEvent(func(e ui.FormEvent) {
		e.PreventDefault()
		submitNow := time.Now()
		next, ok := form.Get().BeginSubmitCode(submitNow)
		if !ok {
			return
		}
		errKey.Set("")
		form.Set(next)

		code := next.Code
		go func() {
			ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
			defer cancel()
			resp, err := props.Client.RecoverWithCode(ctx, &affv1.AuthServiceRecoverWithCodeRequest{RecoveryCode: code})
			completedAt := time.Now()
			if err != nil || resp == nil || resp.Session == nil {
				failedForm := form.Get().CodeFailed(completedAt)
				form.Set(failedForm)
				// Same D0-10 distinction as login.go's handleSubmit — see
				// backoff_display.go's AuthErrorKey doc comment.
				key := AuthErrorKey(shell.IsDisconnected(err), afi18n.KeyCommonGenericAuthError)
				errKey.Set(key)
				announcer.Assertive(tc.T(key))
				remaining := failedForm.RemainingBackoff(completedAt)
				if ShouldAnnounceBackoffStarted(remaining) {
					announcer.Polite(tc.T(afi18n.KeyCommonBackoffNotice, gwci18n.Arguments{"count": BackoffSecondsCeil(remaining)}))
					backoffActive.Set(true)
				}
				focus.FocusSelector("#" + errorID)
				return
			}
			if props.OnElevated != nil {
				props.OnElevated(resp.Session)
			}
			nextForm, ok := form.Get().CodeAccepted(int(resp.RemainingRecoveryCodes))
			if ok {
				form.Set(nextForm)
			}
			announcer.Polite(t.T(afi18n.KeyRecoverChooseActionHeading))
		}()
	})

	handleChoosePasswordReset := ui.UseEvent(func() {
		next, ok := form.Get().ChoosePasswordReset()
		if !ok {
			return
		}
		form.Set(next)
		focus.FocusSelector(recoverFocusSelector(RecoverFocusTargetForStep(next.Step)))
	})
	handleChooseReenrollTOTP := ui.UseEvent(func() {
		next, ok := form.Get().ChooseReenrollTOTP()
		if !ok {
			return
		}
		form.Set(next)
		// Moves focus onto the reenroll step's own heading (tabindex="-1",
		// see RecoverStepReenrollTOTP's render below) — otherwise the
		// choose-action button this click just unmounted leaves focus
		// stranded on nothing, the same class of bug this task flagged.
		focus.FocusSelector(recoverFocusSelector(RecoverFocusTargetForStep(next.Step)))
	})

	handleResetSubmit := ui.UseEvent(func(e ui.FormEvent) {
		e.PreventDefault()
		next, ok := form.Get().BeginSubmitReset()
		if !ok {
			return
		}
		errKey.Set("")
		form.Set(next)

		newPassword := next.NewPassword
		go func() {
			ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
			defer cancel()
			// Elevated session: CurrentPassword/TotpCode are unused server
			// side (identity already re-proven by the recovery code —
			// AuthServiceChangePasswordRequest's doc, mirrored in
			// recover_state.go's CanSubmitReenroll comment for the
			// sibling call).
			_, err := props.Client.ChangePassword(ctx, &affv1.AuthServiceChangePasswordRequest{
				NewPassword: newPassword,
			})
			if err != nil {
				form.Set(form.Get().ResetFailed())
				key := AuthErrorKey(shell.IsDisconnected(err), afi18n.KeyCommonGenericAuthError)
				errKey.Set(key)
				announcer.Assertive(tc.T(key))
				focus.FocusSelector("#" + errorID)
				return
			}
			nextForm, ok := form.Get().ResetSucceeded()
			if ok {
				form.Set(nextForm)
			}
			if props.OnComplete != nil {
				props.OnComplete()
			}
		}()
	})

	handleReenrollSubmit := ui.UseEvent(func() {
		next, ok := form.Get().BeginSubmitReenroll()
		if !ok {
			return
		}
		errKey.Set("")
		form.Set(next)

		go func() {
			ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
			defer cancel()
			resp, err := props.Client.ReenrollTOTP(ctx, &affv1.AuthServiceReenrollTOTPRequest{})
			if err != nil || resp == nil {
				form.Set(form.Get().ReenrollFailed())
				key := AuthErrorKey(shell.IsDisconnected(err), afi18n.KeyCommonGenericAuthError)
				errKey.Set(key)
				announcer.Assertive(tc.T(key))
				focus.FocusSelector("#" + errorID)
				return
			}
			provisioningURI.Set(resp.ProvisioningUri)
			nextForm, ok := form.Get().ReenrollSucceeded()
			if ok {
				form.Set(nextForm)
			}
			if props.OnComplete != nil {
				props.OnComplete()
			}
		}()
	})

	handleToggleSavedConfirm := ui.UseEvent(func(e ui.InputEvent) {
		confirmedSaved.Set(e.IsChecked())
	})

	handleGoToLogin := ui.UseEvent(func() {
		nav.Replace("/login")
	})

	remaining := f.RemainingBackoff(now)
	blocked := remaining > 0

	// Same reasoning as login.go: the countdown announcement is driven by
	// an effect keyed on `blocked` (fires only on an actual value change,
	// never per-tick) plus a one-time start announcement in
	// handleCodeSubmit's failure branch above — never by a live region
	// whose text changes every second.
	ui.UseEffectOf(func() func() {
		if ShouldAnnounceBackoffCleared(blocked, backoffActive.Get()) {
			announcer.Polite(tc.T(keyBackoffCleared))
			backoffActive.Set(false)
		}
		return nil
	}, blocked)

	var errorNode ui.Node
	if errKey.Get() != "" {
		errorNode = h.P(h.ID(errorID), h.Aria("live", "assertive"), h.ClassStr("af-form-error"), tc.T(errKey.Get()))
	} else {
		errorNode = h.P(h.ID(errorID), h.ClassStr("af-form-error"))
	}

	// backoffNode carries no role="status"/aria-live — see login.go's
	// identical comment.
	var backoffNode ui.Node
	if blocked {
		backoffNode = h.P(h.ClassStr("af-backoff-notice"),
			tc.T(afi18n.KeyCommonBackoffNotice, gwci18n.Arguments{"count": BackoffSecondsCeil(remaining)}))
	} else {
		backoffNode = h.P(h.ClassStr("af-backoff-notice"))
	}

	breakGlass := h.Section(
		h.ClassStr("af-recover-breakglass"),
		h.H2(t.T(afi18n.KeyRecoverBreakGlassHeading)),
		h.P(t.T(afi18n.KeyRecoverBreakGlassBody)),
		h.P(h.ClassStr("af-code"), t.T(afi18n.KeyRecoverBreakGlassCommandNote)),
	)

	var body ui.Node
	switch f.Step {
	case RecoverStepEnterCode:
		body = h.Form(
			h.OnSubmit(handleCodeSubmit),
			h.ClassStr("af-auth-form"),
			h.Label(h.For(codeID), t.T(afi18n.KeyRecoverCodeLabel)),
			h.Input(
				h.ID(codeID),
				h.Type("text"),
				h.AutoComplete("off"),
				h.Aria("describedby", codeID+"-hint"),
				h.Value(f.Code),
				h.OnInput(handleCode),
				h.Disabled(f.Submitting),
			),
			h.P(h.ID(codeID+"-hint"), h.ClassStr("af-field-hint"), t.T(afi18n.KeyRecoverCodeHint)),
			h.Button(h.Type("submit"), h.Disabled(!f.CanSubmitCode(now)), t.T(afi18n.KeyRecoverCodeSubmit)),
			errorNode,
			backoffNode,
		)
	case RecoverStepChooseAction:
		var lowCodesNode ui.Node = h.P()
		if f.LowOnCodes() {
			lowCodesNode = h.P(h.Role("status"), h.ClassStr("af-low-codes-warning"), t.T(afi18n.KeyRecoverLowCodesWarning))
		}
		body = h.Div(
			h.ClassStr("af-recover-choice"),
			h.P(h.Role("status"), t.T(afi18n.KeyRecoverRemainingCodes, gwci18n.Arguments{"count": f.RemainingCodes})),
			lowCodesNode,
			h.H2(t.T(afi18n.KeyRecoverChooseActionHeading)),
			h.P(t.T(afi18n.KeyRecoverChooseActionIntro)),
			h.Div(
				h.ClassStr("af-recover-actions"),
				h.Button(h.Type("button"), h.OnClick(handleChoosePasswordReset), t.T(afi18n.KeyRecoverChoosePasswordReset)),
				h.Button(h.Type("button"), h.OnClick(handleChooseReenrollTOTP), t.T(afi18n.KeyRecoverChooseReenrollTOTP)),
				// The way out. Reuses the already-registered handler, so no
				// hook slot moves.
				h.Button(h.Type("button"), h.ClassStr("af-recover-cancel"),
					h.OnClick(handleGoToLogin), t.T(afi18n.KeyRecoverCancel)),
			),
		)
	case RecoverStepResetPassword:
		submitLabel := t.T(afi18n.KeyRecoverResetSubmit)
		if f.Submitting {
			submitLabel = tc.T(afi18n.KeyCommonSubmitting)
		}
		var mismatchNode ui.Node = h.P()
		if f.NewPassword != "" && f.ConfirmPassword != "" && !f.PasswordsMatch() {
			mismatchNode = h.P(h.Role("alert"), h.ClassStr("af-field-error"), t.T(afi18n.KeyRecoverPasswordMismatch))
		}
		body = h.Form(
			h.OnSubmit(handleResetSubmit),
			h.ClassStr("af-auth-form"),
			h.Label(h.For(newPasswordID), t.T(afi18n.KeyRecoverNewPasswordLabel)),
			h.Input(h.ID(newPasswordID), h.Type("password"), h.AutoComplete("new-password"),
				h.Value(f.NewPassword), h.OnInput(handleNewPassword), h.Disabled(f.Submitting)),
			h.Label(h.For(confirmPasswordID), t.T(afi18n.KeyRecoverConfirmPasswordLabel)),
			h.Input(h.ID(confirmPasswordID), h.Type("password"), h.AutoComplete("new-password"),
				h.Value(f.ConfirmPassword), h.OnInput(handleConfirmPassword), h.Disabled(f.Submitting)),
			mismatchNode,
			h.Button(h.Type("submit"), h.Disabled(!f.CanSubmitReset()), submitLabel),
			h.Button(h.Type("button"), h.ClassStr("af-recover-cancel"),
				h.OnClick(handleGoToLogin), t.T(afi18n.KeyRecoverCancel)),
			errorNode,
		)
	case RecoverStepReenrollTOTP:
		submitLabel := t.T(afi18n.KeyRecoverReenrollSubmit)
		if f.Submitting {
			submitLabel = tc.T(afi18n.KeyCommonSubmitting)
		}
		body = h.Div(
			h.ClassStr("af-recover-reenroll"),
			// tabindex="-1": not in tab order, but a valid
			// FocusSelector target — handleChooseReenrollTOTP moves focus
			// here the instant this step's markup mounts, so a keyboard/
			// screen-reader user isn't left on the choose-action button
			// that just unmounted.
			h.H2(h.ID(reenrollHeadingID), h.TabIndex(-1), t.T(afi18n.KeyRecoverReenrollHeading)),
			h.P(t.T(afi18n.KeyRecoverReenrollIntro)),
			h.Button(h.Type("button"), h.OnClick(handleReenrollSubmit), h.Disabled(f.Submitting), submitLabel),
			h.Button(h.Type("button"), h.ClassStr("af-recover-cancel"),
				h.OnClick(handleGoToLogin), t.T(afi18n.KeyRecoverCancel)),
			errorNode,
		)
	case RecoverStepDone:
		isReenroll := provisioningURI.Get() != ""
		var qrNode ui.Node = h.P()
		var confirmNode ui.Node = h.P()
		if isReenroll {
			// The provisioning URI is the "shown once, never retrievable
			// again" secret (PLAN.md §4) — rendered as plain selectable
			// text (readable, copyable via ordinary text selection, and
			// printable like any other on-screen text; no extra affordance
			// needed for any of the three). "Go to sign in" below stays
			// disabled until the checkbox confirms it was saved, so a
			// stray click can't navigate away from the only screen this
			// secret is ever shown on — losing it means break-glass on the
			// box is the only way back in (recover.breakGlassBody, below).
			qrNode = h.P(h.ClassStr("af-code"), t.T(afi18n.KeyRecoverReenrollProvisioned, gwci18n.Arguments{"uri": provisioningURI.Get()}))
			confirmNode = h.Div(
				h.ClassStr("af-recover-saved-confirm"),
				h.Input(
					h.ID(savedConfirmID),
					h.Type("checkbox"),
					h.Checked(confirmedSaved.Get()),
					h.OnChange(handleToggleSavedConfirm),
				),
				h.Label(h.For(savedConfirmID), t.T(keyRecoverSavedConfirm)),
			)
		}
		goToLoginDisabled := isReenroll && !confirmedSaved.Get()
		body = h.Div(
			h.ClassStr("af-recover-done"),
			h.H2(t.T(afi18n.KeyRecoverDoneHeading)),
			h.P(t.T(afi18n.KeyRecoverDoneBody)),
			qrNode,
			confirmNode,
			h.Button(h.Type("button"), h.OnClick(handleGoToLogin), h.Disabled(goToLoginDisabled), t.T(afi18n.KeyRecoverDoneGoToLogin)),
		)
	}

	return h.Main(
		h.ClassStr("af-auth-page"),
		announcer.Region(),
		renderAuthBrand(),
		h.H1(t.T(afi18n.KeyRecoverTitle)),
		h.P(t.T(afi18n.KeyRecoverIntro)),
		body,
		breakGlass,
	)
}
